name: lab 5 - times table

on:
  push:
    branches:
      - main

jobs:
  times_table:
    runs-on: ubuntu-latest
    steps:
      - name: Print 5 times table
        run: |
          for i in {1..10}; do
            echo "1 x $i = $((1 * i))"
          done
