name: lab 5

on:
  push:
    branches:
      - main

jobs:
  times_tabl:
    runs-on: ubuntu-latest
    steps:
      - name: Print 5 times table
        run: |
          for i in {1..10}; do
            echo "5 x $i = $((5 * i))"
          done



